#!/bin/sh

set -e

systemd-tmpfiles --create /usr/lib/tmpfiles.d/lirc.conf || :

for f in lircd.conf lircmd.conf irexec.lircrc; do
    test -e /etc/lirc/$f || cp /etc/lirc/${f}.dist /etc/lirc/$f || :
done

python3 -m compileall  /usr/lib/*/python3/dist-packages/lirc/


#DEBHELPER#
