#!/bin/sh

set -e

if test "$1" = 'purge'; then
    for f in lircd.conf lircmd.conf irexec.lircrc lirc_options.conf; do
	rm -f /etc/lirc/$f;
    done || :
    find /etc/lirc -type d -empty -delete || :
fi


#DEBHELPER#

